/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.modelsDaftarPanel.*;

import controller.*;
import models.*;
import models.jimat.*;
/**
 *
 * @author WINDOWS
 */
public class PanelSuplierMenu extends javax.swing.JPanel {
    GameManager gm;
    /**
     * Creates new form PanelSuplierMenu
     */
    public PanelSuplierMenu() {
        initComponents();
        
    }
    
    public PanelSuplierMenu(GameManager gm) {
        this.gm =gm;
        initComponents();
        
        if (gm != null && gm.getSupplier().getBahanBaku() != null){
            for (RawMaterial rw : gm.getSupplier().getBahanBaku()){
                jPanel3.add(new PanelUntukDaftarMenu(rw,gm));
            }   
        }
    }

    public void masukJP3(PanelUntukDaftarMenu p){
        jPanel3.add(p);
    }
    
    public void masukJP4(){
        
    }

    public JPanel getJPanel3(){
        return jPanel3;
    }
    
    //dumy method
    private JPanel createItemCard(String name, String qty) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(255, 253, 228));
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        
        // Icon (Hanya kotak placeholder, kamu bisa ganti dengan ImageIcon)
        JLabel lblIcon = new JLabel("🍪", JLabel.CENTER);
        lblIcon.setFont(new Font("Serif", Font.PLAIN, 40));
        
        // Label Angka/Qty (Pojok kanan bawah)
        JLabel lblQty = new JLabel(qty + "  ", JLabel.RIGHT);
        lblQty.setFont(new Font("Arial", Font.BOLD, 16));

        card.add(lblIcon, BorderLayout.CENTER);
        card.add(lblQty, BorderLayout.SOUTH);

        return card;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 30, 42));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 20, 1));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 1, 1));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel5.setLayout(null);

        jLabel2.setText("jLabel2");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(210, 60, 37, 16);

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel5.add(jButton1);
        jButton1.setBounds(190, 110, 75, 23);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab2", jPanel2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p = (int) (Math.random()*3)+1;
        switch (p) {
            case 1:
                gm.getRestaurant().beli(gm.getSupplier(), new Charming());
            return;
            case 2:
                gm.getRestaurant().beli(gm.getSupplier(), new Security());
            return;
            case 3:
                gm.getRestaurant().beli(gm.getSupplier(), new Cleaner());
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
