/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author WINDOWS
 */
public class PanelSuplierMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelSuplierMenu
     */
    public PanelSuplierMenu() {
        initComponents();
        
        // dummy
        for(int i = 0 ; i < 20 ; i++){
            container.add(createItemCard("Nigas","2"));
        }
        
    }
    
    //dumy method
        private JPanel createItemCard(String name, String qty) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(255, 253, 228));
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        
        // Icon (Hanya kotak placeholder, kamu bisa ganti dengan ImageIcon)
        JLabel lblIcon = new JLabel("🍪", JLabel.CENTER);
        lblIcon.setFont(new Font("Serif", Font.PLAIN, 40));
        
        // Label Angka/Qty (Pojok kanan bawah)
        JLabel lblQty = new JLabel(qty + "  ", JLabel.RIGHT);
        lblQty.setFont(new Font("Arial", Font.BOLD, 16));

        card.add(lblIcon, BorderLayout.CENTER);
        card.add(lblQty, BorderLayout.SOUTH);

        return card;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        setBackground(new java.awt.Color(26, 30, 42));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 20, 1));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        container.setBackground(new java.awt.Color(26, 30, 42));
        container.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 3, 10, 3));
        container.setAutoscrolls(true);
        container.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.LINE_AXIS));
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(container);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
