/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author WINDOWS
 */
public class PanelRestoranMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelPermainan
     */
    public PanelRestoranMenu() {
        initComponents();
        
    for (int i = 1; i <= 20; i++) {
            container.add(createItemCard("l","lo"));
        }
        
        container.revalidate();
        container.repaint();
    }
    
    
    // masih uji coba
    private JPanel createItemCard(String name, String qty) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(255, 253, 228));
        
        // Icon (Hanya kotak placeholder, kamu bisa ganti dengan ImageIcon)
        JLabel lblIcon = new JLabel("🍪", JLabel.CENTER);
        lblIcon.setFont(new Font("Serif", Font.PLAIN, 40));
        
        // Label Angka/Qty (Pojok kanan bawah)
        JLabel lblQty = new JLabel(qty + "  ", JLabel.RIGHT);
        lblQty.setFont(new Font("Arial", Font.BOLD, 16));

        card.add(lblIcon, BorderLayout.CENTER);
        card.add(lblQty, BorderLayout.SOUTH);

        return card;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel(new GridLayout(0, 3, 15, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        setBackground(new java.awt.Color(26, 30, 42));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new java.awt.BorderLayout());

        jSplitPane2.setBackground(new java.awt.Color(26, 30, 46));
        jSplitPane2.setDividerLocation(0.5);
        jSplitPane2.setDividerSize(6);
        jSplitPane2.setResizeWeight(0.5);
        jSplitPane2.setEnabled(false);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("jButton2");
        jPanel3.add(jButton2);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jSplitPane2.setRightComponent(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("TOMBOL\nUPGRADE"); // NOI18N
        jButton1.setMinimumSize(new java.awt.Dimension(131, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(131, 60));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel4.add(jButton1);

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("UPGRADE RUMAH");
        jPanel4.add(jLabel2);

        jSplitPane2.setLeftComponent(jPanel4);

        add(jSplitPane2, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(26, 30, 42));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 10, 1));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTORI");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBorder(BorderFactory.createLineBorder(new Color(139, 69, 19), 3));
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16); // Scroll halus

        container.setBackground(new java.awt.Color(41, 33, 45));
        container.setLayout(new java.awt.GridLayout(1, 0));
        container.setLayout(new java.awt.GridLayout(0, 4, 15, 15));
        jScrollPane2.setViewportView(container);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
