/*
 * Click nbfs://nbhost    @Override
    public void paintIcon(Component c, Graphics g, int x, int y) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getIconWidth() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getIconHeight() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.modelsDaftarPanel;

import models.*;
import javax.swing.*;
/**
 *
 * @author WINDOWS
 */
public class PanelDaftarResep extends javax.swing.JPanel {
    String png;
    String name;
    
    int nilaiKuantitas = 1;
    /**
     * Creates new form PanelUntukDaftarMenu
     */
    public PanelDaftarResep(String png, String name ) {
        this.png = png;
        this.name = name;
        initComponents();
        
        if (png != null && getClass().getResource(png) != null) {
            javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(getClass().getResource(png));
            java.awt.Image gambarSesuai = iconAsli.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            jLabel1.setIcon(new javax.swing.ImageIcon(gambarSesuai));
        }
    }
    
    public PanelDaftarResep(RawMaterial rw, Integer qty) {
        initComponents();
        jTextField1.setText(String.valueOf(qty));
        
    }

    public PanelDaftarResep() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 3, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), javax.swing.BorderFactory.createEmptyBorder(1, 4, 2, 1)));
        setMaximumSize(new java.awt.Dimension(1000, 70));
        setMinimumSize(new java.awt.Dimension(227, 70));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 70));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Aset/tes.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jLabel1);

        jPanel1.setOpaque(false);

        jLabel2.setText("tes");

        jTextField1.setText("1");
        jTextField1.setPreferredSize(new java.awt.Dimension(50, 20));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("-");
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("+");
        jButton2.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil teks dari field dan konversi ke integer
            int currentVal = Integer.parseInt(jTextField1.getText().trim());
            
            // 2. Tambahkan nilainya
            nilaiKuantitas = currentVal + 1;
        
            // 3. Set kembali angka terbaru ke teks field
            jTextField1.setText(String.valueOf(nilaiKuantitas));
            jButton1.setEnabled(true);
        } catch (NumberFormatException e) {
            // Jika teks field kosong atau bukan angka, reset ke angka 1
            nilaiKuantitas = 1;
            jTextField1.setText("1");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

        try {
            // Ambil nilai yang diketik manual oleh user
            nilaiKuantitas = Integer.parseInt(jTextField1.getText().trim());
        } catch (NumberFormatException e) {
            // Jika yang diketik bukan angka, kembalikan ke nilai aman terakhir
            jTextField1.setText(String.valueOf(nilaiKuantitas));
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
                // 1. Ambil teks dari field dan konversi ke integer
            int currentVal = Integer.parseInt(jTextField1.getText().trim());
            
            // 2. Kurangi nilainya jika masih di atas 1 (Batas minimal angka 1)
            if (currentVal > 1) {
                nilaiKuantitas = currentVal - 1;
            } else {
                nilaiKuantitas = 1; // Kunci di angka 1 jika dipaksa
            }
        
            // 3. Set kembali angka terbaru ke teks field
            jTextField1.setText(String.valueOf(nilaiKuantitas));
        
            // 4. CEK KONDISI SEKARANG: Jika hasil akhirnya sudah 1, langsung matikan tombol
            if (nilaiKuantitas <= 1) {
                jButton1.setEnabled(false);
            } else {
                jButton1.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            // Jika teks field kosong atau bukan angka, reset ke angka 1
            nilaiKuantitas = 1;
            jTextField1.setText("1");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public int getNilaiKuantitas(){
        return nilaiKuantitas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
