package view.modelsDaftarPanel;

import java.awt.Color;
import java.awt.Component;
import javax.swing.*;
import models.jimat.*;
/**
 *
 * @author WINDOWS
 */
public class PanelInventarisJimat extends javax.swing.JPanel implements ListCellRenderer<Jimat> {

    /**
     * Creates new form PanelUntukDaftarMenu
     */
    public PanelInventarisJimat() {

        initComponents();
    }
    
    @Override
    public Component getListCellRendererComponent(
            JList<? extends Jimat> list, 
            Jimat jimat, 
            int index, 
            boolean isSelected, 
            boolean cellHasFocus) {
        
        // Cek validasi data untuk menghindari NullPointerException
        if (jimat != null) {
            jLabel2.setText(jimat.getName());
            jLabel3.setText(String.format("Power : %.1f", jimat.getPower()));
            
            // Contoh opsional: jika Anda punya ikon/gambar di class Jimat
            // jLabel1.setIcon(jimat.getIcon()); 
        }

        // 2. Mengatur efek visual saat item dipilih (diklik) pengguna
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            jLabel2.setForeground(list.getSelectionForeground());
            jLabel3.setForeground(list.getSelectionForeground());
            setOpaque(true); // Agar background warna seleksi terlihat
        } else {
            setBackground(list.getBackground());
            jLabel2.setForeground(list.getForeground());
            jLabel3.setForeground(Color.GRAY); // Power diberi warna abu-abu agar estetik
            setOpaque(false); // Mengembalikan ke settingan awal Anda (false)
        }

        return this; // Mengembalikan panel ini sebagai representasi visual baris list
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 70));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        add(jLabel1);

        jPanel1.setOpaque(false);

        jLabel2.setText("Nama JImat");

        jLabel3.setText("Power : 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
